# Generated by Django 5.1.1 on 2024-09-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Savol Darajasi')),
                ('number', models.IntegerField(verbose_name='Savol Raqami')),
                ('vairant_size', models.IntegerField(default=1, verbose_name='Variant foto size')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Asosiy Savol matni')),
                ('sub_text', models.TextField(blank=True, null=True, verbose_name='Sub Savol matni')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='question', verbose_name='Savol Rasmi')),
                ('question_size', models.IntegerField(default=1, verbose_name='Foto size')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Javob matni')),
                ('foto_answear', models.ImageField(blank=True, null=True, upload_to='question', verbose_name='Javob Rasmi')),
                ('option_one', models.TextField(blank=True, null=True, verbose_name='1-variant')),
                ('foto_one', models.ImageField(blank=True, null=True, upload_to='question', verbose_name='1-variant rasmi')),
                ('option_two', models.TextField(blank=True, null=True, verbose_name='2-variant')),
                ('foto_two', models.ImageField(blank=True, null=True, upload_to='question', verbose_name='2-variant rasmi')),
                ('option_three', models.TextField(blank=True, null=True, verbose_name='3-variant')),
                ('foto_three', models.ImageField(blank=True, null=True, upload_to='question', verbose_name='3-variant rasmi')),
            ],
        ),
    ]
